%% LAP_SIM
% This script creates a rudimentary lap sim by accounting for the losses in
% lateral acceleration due to lateral load transfer. This script mostly
% lays out the user interface of the lap sim.

%% Define Car and Global Parameters

path(path,'GUI Files'); % add path to find gui functions
path(path,'SIM Files'); % add path to find lap sim functions

global car;
car = car_struct(); 

%% Create GUI Figure and all car text boxes 

SCR = get(0,'Screensize');  % Get screensize.
fig.height = 360;
fig.width = 800;
fig.fh = figure('units','pixels',...
              'position',[SCR(3)/2-400 ,SCR(4)/2-180 , fig.width, fig.height],...
              'menubar','none',...
              'name','Lap Simulator',...
              'numbertitle','off',...
              'resize','off');

% gui title
fig.title = uicontrol('style','text',...
    'unit','pix',...
    'position',[0 (fig.height-30) fig.fh.Position(3) 22],...
    'min',0,'max',2,...
    'fontsize',22,...
    'string', 'Blake Leiker''s Incredible Lap Simulator',...
    'FontWeight', 'Bold');

% car weight
fig.tx(1) = uicontrol('style','text',...
    'unit','pix',...
    'position',[10 (fig.height-90) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Weight [lbs]');
fig.ed(1) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[210 (fig.height-90) 100 22],...
    'fontsize',18,...
    'string',car.W);

% car unsprung weight
fig.tx(2) = uicontrol('style','text',...
    'unit','pix',...
    'position',[10 (fig.height-120) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Unsprung Weight [lbs]');
fig.ed(2) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[210 (fig.height-120) 100 22],...
    'fontsize',18,...
    'string',car.W1);

% car wheelbase
fig.tx(3) = uicontrol('style','text',...
    'unit','pix',...
    'position',[10 (fig.height-150) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Wheelbase [in]');
fig.ed(3) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[210 (fig.height-150) 100 22],...
    'fontsize',18,...
    'string',car.l);

% car cg height
fig.tx(4) = uicontrol('style','text',...
    'unit','pix',...
    'position',[10 (fig.height-180) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'CG Height [in]');
fig.ed(4) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[210 (fig.height-180) 100 22],...
    'fontsize',18,...
    'string',car.h);

% car front roll center
fig.tx(5) = uicontrol('style','text',...
    'unit','pix',...
    'position',[10 (fig.height-210) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Front Roll Center [in]');
fig.ed(5) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[210 (fig.height-210) 100 22],...
    'fontsize',18,...
    'string',car.rc_front);

% car rear roll center
fig.tx(6) = uicontrol('style','text',...
    'unit','pix',...
    'position',[10 (fig.height-240) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Rear Roll Center [in]');
fig.ed(6) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[210 (fig.height-240) 100 22],...
    'fontsize',18,...
    'string',car.rc_rear);

% car tire spring rate
fig.tx(7) = uicontrol('style','text',...
    'unit','pix',...
    'position',[10 (fig.height-270) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Tire Spring Rate [lb/in]');
fig.ed(7) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[210 (fig.height-270) 100 22],...
    'fontsize',18,...
    'string',car.k1);

% car motion ratio
fig.tx(8) = uicontrol('style','text',...
    'unit','pix',...
    'position',[330 (fig.height-90) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Motion Ratio');
fig.ed(8) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[530 (fig.height-90) 100 22],...
    'fontsize',18,...
    'string',car.MR);

% car damping rate
fig.tx(9) = uicontrol('style','text',...
    'unit','pix',...
    'position',[330 (fig.height-120) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Damping Rate [lb/in/s]');
fig.ed(9) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[530 (fig.height-120) 100 22],...
    'fontsize',18,...
    'string',car.damper_rate);

% car front track width
fig.tx(10) = uicontrol('style','text',...
    'unit','pix',...
    'position',[330 (fig.height-150) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Front Track Width [in]');
fig.ed(10) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[530 (fig.height-150) 100 22],...
    'fontsize',18,...
    'string',car.tf);

% car rear track width
fig.tx(11) = uicontrol('style','text',...
    'unit','pix',...
    'position',[330 (fig.height-180) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Rear Track Width [in]');
fig.ed(11) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[530 (fig.height-180) 100 22],...
    'fontsize',18,...
    'string',car.tr);

% car front spring rate
fig.tx(12) = uicontrol('style','text',...
    'unit','pix',...
    'position',[330 (fig.height-210) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Front Spring Rate [lb/in]');
fig.ed(12) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[530 (fig.height-210) 100 22],...
    'fontsize',18,...
    'string',car.spring_rate_front);

% car rear spring rate
fig.tx(13) = uicontrol('style','text',...
    'unit','pix',...
    'position',[330 (fig.height-240) 200 22],...
    'fontsize',18,...
    'HorizontalAlignment','left',...
    'string', 'Rear Spring Rate [lb/in]');
fig.ed(13) = uicontrol('style','edit',...
    'unit','pix',...
    'position',[530 (fig.height-240) 100 22],...
    'fontsize',18,...
    'string',car.spring_rate_rear);

set(fig.ed(:),'callback',{@input_box_callback,fig}); 

%% Create Update Car button

fig.update_car = uicontrol('style','pushbutton',...
    'unit','pix',...
    'position',[60 50 150 28],...
    'fontsize',20,...
    'string', 'Update Car',...
    'callback', {@update_car,fig});

%% Create Run Lap Sim button

fig.run_sim = uicontrol('style','pushbutton',...
    'unit','pix',...
    'position',[60 20 150 28],...
    'fontsize',20,...
    'string', 'Run Lap Sim',...
    'callback', @run_Lap_Sim);

%% Display Message Output box

fig.message = uicontrol('style','edit',...
    'unit','pix',...
    'position',[250 20 500 58],...
    'Max',2,...
    'fontsize',18,...
    'enable','inactive',...
    'HorizontalAlignment','Left',...
    'String', {'Welcome to Blake Leiker''s Incredible Lab Simulator!'});

%% Toggle Tabs for about message

fig.toggle(1) = uicontrol('style','toggle',...
    'units','pixels',...
    'position',[5 fig.height-35 60 30],...
    'string','STUFF',...
    'val',1,...
    'callback',@toggle_callback);

fig.toggle(2) = uicontrol('style','toggle',...
    'units','pixels',...
    'position',[65 fig.height-35 60 30],...
    'string','ABOUT',...
    'val',0,...
    'enable','on',...
    'callback',@toggle_callback);

about_msg = ...
   ['    This program is a lap simulator originally designed for the 2017 TAMU '...
    'FSAE team. This lap simulator divides the 2014 Lincoln Endurance track '...
    'into a series of straights, slaloms, and arcs to calculate the total '...
    'track time. This sim relies heavily on the principle of tire load '...
    'sensitivity; using the known car parameters, the total load transfer of '...
    'the car is calculated, which is then used to calulate the amount of g''s '...
    'that the tires are able to generate.                                                      '...
    '         Car parameters turn yellow when they have been edited. This indicates '...
    'that the edited field is different that the saved car parameters. '...
    'Press the "Update Car" button to update the car data structure with '...
    'input parameters.'];

fig.about = uicontrol('style','text',...
    'units','pixels',...
    'position',[20 50 fig.width-40 fig.height-100],...
    'min',0,'max',2,...
    'horizontalalignment','left',...
    'fontsize',18,...
    'string',about_msg,...
    'visible','off');
%% save gui data

guidata(fig.fh,fig)
